### ISSUE TITLE
Vars in custom-media not resolved

### ISSUE THREAD

**Issue by VinSpee** [postcss/postcss-simple-vars#3]
### INPUT:
```css
$palm : (min-width: var(--ms6));
@custom-media --palm (min-width: $palm);

@media (--palm) {
    html {
         background: red !important;
    }
  }

```

### OUTPUT:
```css
@media (min-width: $palm) {
    html {
         background: red !important;
    }
  }
```

I would expect that this variable is resolved. my plugin order:
```js
    .pipe(postcss([
      inline({
        path: ['./app/styles/']
      }),
      nested,
      simpleVars(),
      customProperties(),
      customMedia(),
      calc(),
      gray(),
      colorHexAlpha(),
      colorFunction(),
      fontVariant(),
      autoprefixer({ browsers: 'last 2 versions' })
    ]))
```

**Comment by ai** [comment]
Fixed 21a4d960f0615720ab0427310d19d6db540aace8

**Comment by VinSpee** [comment]
thanks @ai. What's your NPM patch release cycle like?

**Comment by ai** [comment]
Of course, I am waiting for Travis CI finish :).

**Comment by ai** [comment]
Released in 0.2.4.

**Comment by VinSpee** [comment]
still having this issue after updating to v0.2.4.

```bash
 $ npm list --depth=0 | ag postcss-simple-vars
├── postcss-simple-vars@0.2.4
```
### CONFIG:
```js
    .pipe(postcss([
      inline({
        path: ['./app/styles/']
      }),
      simpleVars(),
      nested,
      customProperties(),
      customMedia(),
      calc(),
      gray(),
      colorHexAlpha(),
      colorFunction(),
      fontVariant(),
      autoprefixer({ browsers: 'last 2 versions' })
    ]))

```

### INPUT:
```css
$palm : (min-width: var(--ms6));
$lap  : (min-width: var(--ms7));
$desk : (min-width: var(--ms8));
$wall : (min-width: var(--ms9));

@custom-media --palm (min-width: $palm);
@custom-media --lap  (min-width: $lap);
@custom-media --desk (min-width: $desk);
@custom-media --wall (min-width: $wall);

.🐜--mqs {
  background: lime !important;
  @media (--palm) {
    background: red !important;
  }
  @media (--lap) {
    background: blue !important;
  }
  @media (--desk) {
    background: pink !important;
  }
  @media (--wall) {
    background: yellow !important;
  }
}
```
### OUTPUT:
```css
$palm : (min-width: var(--ms6));
$lap  : (min-width: var(--ms7));
$desk : (min-width: var(--ms8));
$wall : (min-width: var(--ms9));

@custom-media --palm (min-width: $palm);
@custom-media --lap  (min-width: $lap);
@custom-media --desk (min-width: $desk);
@custom-media --wall (min-width: $wall);

.🐜--mqs {
  background: lime !important;
  @media (--palm) {
    background: red !important;
  }
  @media (--lap) {
    background: blue !important;
  }
  @media (--desk) {
    background: pink !important;
  }
  @media (--wall) {
    background: yellow !important;
  }
}
```

Any Ideas?

**Comment by ai** [comment]
You have some problem with CSS processing. Simple vars plugin removes any variables from output. Custom media plugin removes `@custom-media` at-rules. If they are still in output, this plugin was no be runned.

**Comment by VinSpee** [comment]
I'm sorry, my mistake. The @custom-media declarations aren't in the output. I updated my comment to fix that - the "output" is now what is actually compiled.

**Comment by VinSpee** [comment]
It is a problem with my processing order. thank you!

**Comment by VinSpee** [comment]
for anyone having issues that may stumble upon this, I needed this order:

```js
customProperties(),
calc(),
simpleVars(),
customMedia()
```
